;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Game.Beach.Lighter",NewTagName="Game.Beach.Interactor.Lighter")
+GameplayTagRedirects=(OldTagName="Game.Beach.Blanket",NewTagName="Game.Beach.Interactor.Blanket")
+GameplayTagRedirects=(OldTagName="Action.Beach.LightUptLighter",NewTagName="Action.Beach.Lighter")
+GameplayTagRedirects=(OldTagName="Action.Beach.PutBlanket",NewTagName="Action.Beach.Blanket")
+GameplayTagList=(Tag="Action.Beach.Blanket",DevComment="")
+GameplayTagList=(Tag="Action.Beach.Lighter",DevComment="")
+GameplayTagList=(Tag="Audio",DevComment="")
+GameplayTagList=(Tag="Audio.Player",DevComment="")
+GameplayTagList=(Tag="Event.Beach.LightSparkler",DevComment="")
+GameplayTagList=(Tag="Event.Beach.PutBlanket",DevComment="")
+GameplayTagList=(Tag="Event.Beach.WindFail",DevComment="")
+GameplayTagList=(Tag="Scene.State.Start",DevComment="")
+GameplayTagList=(Tag="Scene.State.TimeUp",DevComment="")
+GameplayTagList=(Tag="Wish.Beach",DevComment="")

